#!/bin/bash
# AEOESS Autoresearch Loop
# Autonomous adversarial hardening for Agent Passport System
#
# Usage: ./autoresearch.sh [--max-iterations N] [--arena adversarial|property|parity]
#
# Prerequisites:
#   - Claude Code installed (npm install -g @anthropic-ai/claude-code)
#   - Inside the agent-passport-system repo
#   - npm dependencies installed

set -euo pipefail

# ── Configuration ──────────────────────────────────────────────
MAX_ITERATIONS=${MAX_ITERATIONS:-100}
ARENA=${ARENA:-adversarial}
REPO_DIR="${REPO_DIR:-$HOME/agent-passport-system}"
AUTORESEARCH_DIR="${REPO_DIR}/autoresearch"
LOG_DIR="${AUTORESEARCH_DIR}/logs"
RESULTS_FILE="${AUTORESEARCH_DIR}/results.jsonl"
BRANCH="autoresearch-${ARENA}-$(date +%Y%m%d-%H%M%S)"

# Parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    --max-iterations) MAX_ITERATIONS="$2"; shift 2 ;;
    --arena) ARENA="$2"; shift 2 ;;
    --repo) REPO_DIR="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# ── Setup ──────────────────────────────────────────────────────
cd "$REPO_DIR"
mkdir -p "$LOG_DIR"

# Create feature branch (like Karpathy's approach)
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

# Initialize the test file if it doesn't exist
TEST_FILE="tests/autoresearch-adversarial.test.ts"
if [ ! -f "$TEST_FILE" ]; then
  cat > "$TEST_FILE" << 'INIT'
/**
 * AEOESS Autoresearch: Autonomous Adversarial Test Suite
 * 
 * This file is maintained by an autonomous research agent.
 * Each test targets a specific protocol invariant with a novel attack vector.
 * 
 * Generated by: autoresearch loop
 * Arena: adversarial hardening
 */

import { describe, test, expect } from 'vitest';
import { generateKeyPair, sign, verify } from '../src/crypto/keys';
import { createPassport, signPassport } from '../src/core/passport';
import { createDelegation, subDelegate, revokeDelegation, cascadeRevoke, validateChain } from '../src/core/delegation';

describe('Autoresearch: Adversarial Hardening', () => {
  // Tests will be added by the autoresearch agent
  test('baseline: test infrastructure works', () => {
    expect(true).toBe(true);
  });
});
INIT
  git add "$TEST_FILE"
  git commit -m "autoresearch: initialize adversarial test file"
fi

# Get baseline test count
BASELINE_TESTS=$(npm test 2>&1 | grep -oP '\d+ tests?' | head -1 | grep -oP '\d+' || echo "0")
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "AEOESS AUTORESEARCH"
echo "Arena: ${ARENA}"
echo "Branch: ${BRANCH}"
echo "Max iterations: ${MAX_ITERATIONS}"
echo "Baseline tests: ${BASELINE_TESTS}"
echo "Started: $(date)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Metrics tracking ───────────────────────────────────────────
ITERATION=0
KEPT=0
DISCARDED=0
BUGS_FOUND=0

# ── The Loop ───────────────────────────────────────────────────
while [ $ITERATION -lt $MAX_ITERATIONS ]; do
  ITERATION=$((ITERATION + 1))
  ITER_LOG="${LOG_DIR}/iteration-${ITERATION}.log"
  TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  
  echo ""
  echo "┌─ Iteration ${ITERATION}/${MAX_ITERATIONS} ─────────────────────────"
  echo "│ Time: ${TIMESTAMP}"
  echo "│ Score: ${KEPT} kept / ${DISCARDED} discarded / ${BUGS_FOUND} bugs"
  echo "└──────────────────────────────────────────────────"
  
  # ── Step 1: Agent writes a new adversarial test ──────────────
  echo "  → Agent generating new adversarial test..."
  
  PROMPT="You are running iteration ${ITERATION} of the AEOESS autoresearch adversarial hardening loop.

Read the program.md file in the autoresearch/ directory for full instructions.

Your task for THIS iteration:
1. Read tests/autoresearch-adversarial.test.ts to see what tests already exist
2. Read tests/adversarial.ts to avoid duplicating existing scenarios  
3. Pick an invariant (INV-1 through INV-8) and an attack category (A-F from program.md)
4. Write ONE new adversarial test that is NOVEL and NON-TRIVIAL
5. Add it inside the existing describe block in tests/autoresearch-adversarial.test.ts
6. Run: npm test
7. Report the result in the exact format specified in program.md

Prioritize under-tested invariants. Check which invariants already have coverage and target gaps.
Iteration ${ITERATION}: be creative. Think like a real attacker."
  
  # Run Claude Code with the prompt
  echo "$PROMPT" | claude --print 2>&1 | tee "$ITER_LOG"
  
  # ── Step 2: Evaluate ─────────────────────────────────────────
  echo "  → Evaluating..."
  
  # Run tests and capture output
  TEST_OUTPUT=$(npm test 2>&1) || true
  TEST_EXIT=$?
  
  # Parse test results
  NEW_TEST_COUNT=$(echo "$TEST_OUTPUT" | grep -oP '\d+ tests?' | head -1 | grep -oP '\d+' || echo "0")
  FAILURES=$(echo "$TEST_OUTPUT" | grep -oP '\d+ failed' | grep -oP '\d+' || echo "0")
  
  echo "  → Tests: ${NEW_TEST_COUNT} (was ${BASELINE_TESTS}), Failures: ${FAILURES}"
  
  # ── Step 3: Keep or Discard ──────────────────────────────────
  if [ "$FAILURES" = "0" ] && [ "$NEW_TEST_COUNT" -gt "$BASELINE_TESTS" ]; then
    # All tests pass AND we added new tests → KEEP
    KEPT=$((KEPT + 1))
    BASELINE_TESTS=$NEW_TEST_COUNT
    RESULT="KEPT"
    
    git add -A
    git commit -m "autoresearch(${ITERATION}): new adversarial test [passed] total=${NEW_TEST_COUNT}" \
      --allow-empty
    
    echo "  ✓ KEPT — new adversarial test added (total: ${NEW_TEST_COUNT})"
    
  elif [ "$FAILURES" != "0" ] && [ "$NEW_TEST_COUNT" -gt "$BASELINE_TESTS" ]; then
    # New test FAILS → potential bug found! Keep it but mark it
    BUGS_FOUND=$((BUGS_FOUND + 1))
    KEPT=$((KEPT + 1))
    BASELINE_TESTS=$NEW_TEST_COUNT
    RESULT="BUG_FOUND"
    
    git add -A
    git commit -m "autoresearch(${ITERATION}): BUG FOUND — adversarial test exposes vulnerability" \
      --allow-empty
    
    echo "  ★ BUG FOUND — adversarial test exposed a vulnerability!"
    
  else
    # No new tests added, or existing tests broke → DISCARD
    DISCARDED=$((DISCARDED + 1))
    RESULT="DISCARDED"
    
    git checkout -- tests/autoresearch-adversarial.test.ts 2>/dev/null || true
    git checkout -- . 2>/dev/null || true
    
    echo "  ✗ DISCARDED — no valid new test or existing tests broken"
  fi
  
  # ── Step 4: Log result ───────────────────────────────────────
  echo "{\"iteration\":${ITERATION},\"timestamp\":\"${TIMESTAMP}\",\"result\":\"${RESULT}\",\"tests\":${NEW_TEST_COUNT},\"failures\":${FAILURES},\"kept\":${KEPT},\"discarded\":${DISCARDED},\"bugs\":${BUGS_FOUND}}" >> "$RESULTS_FILE"
  
  # Brief pause to avoid rate limits
  sleep 2
done

# ── Summary ────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "AUTORESEARCH COMPLETE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Arena:      ${ARENA}"
echo "Iterations: ${ITERATION}"
echo "Kept:       ${KEPT}"
echo "Discarded:  ${DISCARDED}"
echo "Bugs found: ${BUGS_FOUND}"
echo "Final tests: ${BASELINE_TESTS}"
echo "Branch:     ${BRANCH}"
echo "Finished:   $(date)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To review: git log --oneline ${BRANCH}"
echo "To merge:  git checkout main && git merge ${BRANCH}"
